app/blueprints/admin/models.py
from app import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin

class User(db.Model, UserMixin):

    """Data Model for User Login"""
    __tablename__ = 'admin_info'
    id = db.Column("id", db.Integer, primary_key=True)
    username = db.Column("username", db.String(64), index=True, unique=True)
    password_hash = db.Column(db.String)

    def set_password(self, password):
        self.password_hash=generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)
    

class ImageHash(db.Model):
    """Image Hash Table to store the image hash values and corresponding images."""
    __tablename__ = "image_info"
    id = db.Column("id", db.Integer, primary_key=True)
    img_name = db.Column("img_name", db.String(64), nullable=False)
    img_hash = db.Column("img_hash", db.String)

app/blueprints/admin/forms.py
# Admin Related Forms

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, FileField
from wtforms.validators import DataRequired
from flask_wtf.file import FileField, FileAllowed, FileRequired

class LoginForm(FlaskForm):
    """Login Form"""

    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')

class GalleryForm(FlaskForm):
    image = FileField(validators=[
        FileAllowed(['jpg', 'png', 'jpeg'], "Please upload images only"),
        FileRequired()
    ])
    submit_btn = SubmitField("Upload")

app/blueprints/admin/__init__.py
# adding an admin blueprint

from flask import Blueprint, render_template, request, flash, redirect, url_for
from app.models import Customer
from .models import User, ImageHash
from .forms import GalleryForm, LoginForm
from .firebase import File
from flask_login import login_user, login_required, logout_user

admin_page = Blueprint('admin', __name__, template_folder='templates/', static_folder='static/')

@admin_page.route("/", methods=['GET', 'POST'])
@admin_page.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        username = request.form['username']
        password = request.form['password']
        user = User.query.filter_by(username=username).first()
        if user and user.check_password(password):
            login_user(user)
            flash("Login Successful", "success")
            return redirect(request.args.get('next') or url_for('admin.admin_dashboard'))
        else:
            flash("Invalid Credentials", "danger")
            return redirect(url_for('admin.login'))
    return render_template("login.html", form=form)

@admin_page.route('/logout/')
@login_required
def logout():
    logout_user()
    flash("You have been logged out", "success")
    return redirect(url_for('admin.login'))


@admin_page.route('/dashboard/')
@login_required
def admin_dashboard():
    return render_template('dashboard.html')


@admin_page.route('/customer-list/')
@login_required
def customer_list():
    customers = Customer.query.all()
    return render_template('customer_details.html', customers=customers)


@admin_page.route('/admin-gallery/', methods=['GET', 'POST'])
@login_required
def gallery_list():
    form = GalleryForm()
    if form.validate_on_submit():
        image = form.image.data
        if not image:
            flash(f"No file selected for uploading")
            return redirect(url_for("admin.gallery_list"))
        else:
            File().image_upload(image)
            flash(f"Image Uploaded Successfully", "success")
            return redirect(url_for("admin.gallery_list"))
    
    image_info = ImageHash.query.all()
    return render_template('admin_gallery.html', form=form, image_info=image_info)

app/blueprints/admin/templates/admin_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='images/favicon.ico')}}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/alpinejs@2.x.x/dist/alpine.js" defer></script>
    {% block head %}{% endblock %}
</head>
<body>
    {% block body %}{% endblock %}
</body>
</html>

app/blueprints/admin/templates/admin_gallery.html
{% extends 'admin_base.html' %}

{% block title %}
Gallery Info
{% endblock %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('admin.static', filename='styles/admin.css') }}">
<script src="{{ url_for('admin.static', filename='js/index.js') }}" defer></script>
{% endblock %}

{% block body %}

<div class="col-md-6 mx-auto" id="flash-message">
    {% with messages = get_flashed_messages(with_categories=['danger']) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="alert alert-{{ category }} text-center m-2">
                {{ message }}
            </div>
        {% endfor%}
    {% endif %}
{% endwith %}
</div>

<div class="container-fluid container d-flex flex-column" x-data="{ goBack: function() { window.location.href = '{{url_for('admin.admin_dashboard')}}' } }">
    <h2 class="text-center m-3">Admin Gallery</h2>
    <form method="POST" enctype="multipart/form-data">
        {{ form.csrf_token() }}
        <!-- Form File -->
        {{ form.image.label(class="form-control-label") }}
        {{ form.image(class="form-control form-control-md") }}
        <!-- Form Submit -->
        {{ form.submit_btn(class="btn btn-primary col-2 my-2 btn-md") }}
    </form>
    <button class="btn btn-success btn-md back-btn" @click="goBack">
        <i class="bi bi-arrow-left">
            Back
        </i>
    </button>

    <table class="table table-striped table-hover table-responsive-md gallery-table">
        <thead>
            <tr class="table-primary">
                <th scope="col">ID</th>
                <th scope="col">FileName</th>
                <th scope="col">Image Hash</th>
            </tr>
        </thead>
        <tbody>
            {% for image in image_info %}
            <tr class="table-responsive table-secondary">
                <th scope="row">{{ image.id }}</th>
                <td>{{ image.img_name }}</td>
                <td>{{ image.img_hash }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <a href="{{ url_for('admin.logout') }}">
        <button class="btn btn-outline-info">Logout</button>
    </a>
</div>
{% endblock %}

app/blueprints/admin/templates/blog_upload.html
{% extends 'admin_base.html' %}

{% block title %}
Admin Blog
{% endblock %}

{% block head %}
<script type="text/javascript" src="{{ url_for('admin.static', filename='js/index.js')}}" defer></script>
{% endblock %}


{% block body %}
<div class="container container-fluid my-4" x-data="{ goBack: function() { window.history.back(); } }">

    <div class="col-md-6 mx-auto" id="flash-message">
		{% with messages = get_flashed_messages(with_categories=true) %}
		{% if messages %}
			{% for category, message in messages %}
				<div class="alert alert-{{ category }} text-center m-2">
					{{ message }}
				</div>
			{% endfor%}
		{% endif %}
	{% endwith %}
    </div>

    <h2 class="text-center">Admin Blog List</h2>
    <form action="/admin-blog" method="POST">
        {{ form.csrf_token() }}
        {{ form.hidden_tag() }}
        <!-- Blog Title -->
        {{ form.blog_title.label(class="form-control-label") }}
        {{ form.blog_title(class="form-control form-control-md", placeholder="Min Length= 5 letters") }}
        <!-- Blog Body -->
        {{ form.blog_body.label(class="form-control-label") }}
        {{ form.blog_body(class="form-control form-control-md", placeholder="Min Length= 100 letters") }}
        <!--Submit Button-->
        {{ form.blog_submit(class="btn btn-primary col-2 my-2 btn-md") }}
    </form>

    <button class="btn btn-success btn-md back-btn" @click="goBack">
        <i class="bi bi-arrow-left">
            Back
        </i>
    </button>
</div>
{% endblock %}

app/blueprints/admin/templates/customer_details.html
{% extends 'admin_base.html' %}

{% block title %}
Customer Info
{% endblock%}

{% block head %}
<link rel="stylesheet" href="{{ url_for('admin.static', filename='styles/admin.css') }}">
{% endblock %}


{% block body %}
	<div class="d-flex flex-column justify-content-center" x-data="{ goBack: function() { window.location.href = '{{url_for('admin.admin_dashboard')}}' } }">
		<h2 class="text-center m-3">Customer List</h2>
		<table class="table table-striped table-hover table-responsive-md customer-table">
			<thead>
				<tr class="table-primary">
					<th scope="col">ID</th>
					<th scope="col">Name</th>
					<th scope="col">Phone Number</th>
					<th scope="col">Email</th>
					<th scope="col">Remarks</th>
				</tr>
			</thead>
			<tbody>
				{% for customer in customers %}
					<tr class="table-responsive table-secondary">
						<th scope="row">{{ customer.id }}</th>
						<td>{{ customer.name }}</td>
						<td>{{ customer.contact }}</td>
						<td>{{ customer.email }}</td>
						<td>{{ customer.remarks }}</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
		<button class="btn btn-success btn-md back-btn" @click="goBack">
			<i class="bi bi-arrow-left">
				Back
			</i>
		</button>
	</div>

	<!-- <script>
		function goBack(){
			window.history.back();
		}
	</script> -->
{% endblock %}

app/blueprints/admin/templates/dashboard.html
{% extends 'admin_base.html' %}
{% block title %}
	Admin Dashboard
{% endblock %}
{% block head %}
	<script type="text/javascript" src="{{ url_for('admin.static', filename='js/index.js')}}"></script>
{% endblock %}
{% block body %}
	<div class="col-md-6 mx-auto" id="flash-message">
		{% with messages = get_flashed_messages(with_categories=true) %}
		{% if messages %}
			{% for category, message in messages %}
				<div class="alert alert-{{ category }} text-center m-2">
					{{ message }}
				</div>
			{% endfor%}
		{% endif %}
	{% endwith %}
</div>
<div class="container-fluid d-flex flex-column">
	<h1 class="text-center">Welcome To Admin Page</h1>
	<div class="d-flex flex-column justify-content-center align-content-center">
		<a href="{{ url_for('admin.customer_list')}}">
			<button class="btn btn-primary my-2">
				Customer List
			</button>
		</a>
		<a href="{{ url_for('admin.gallery_list')}}">
			<button class="btn btn-primary my-2">
				Gallery List
			</button>
		</a>
		<a href="{{ url_for('admin.logout') }}">
        	<button type="logout" class="btn btn-outline-info my-2">Logout</button>
   		</a>
	</div>
</div>
{% endblock %}

app/blueprints/admin/templates/login.html
{% extends 'admin_base.html'%}
{% block title %}
	Admin Login
{% endblock %}

{% block head %}
<script type="text/javascript" src="{{ url_for('admin.static', filename='js/index.js')}}"></script>
{% endblock %}
{% block body %}
<div class="col-md-6 mx-auto" id="flash-message">
		{% with messages = get_flashed_messages(with_categories=['danger']) %}
		{% if messages %}
			{% for category, message in messages %}
				<div class="alert alert-{{ category }} text-center m-2">
					{{ message }}
				</div>
			{% endfor%}
		{% endif %}
	{% endwith %}
</div>


<div class="container-fluid container d-flex flex-column" style="width:50vw; margin: 2rem auto;">
	<h1 class="text-center">Admin Login</h1>	
	<form method="POST" action="">
		{{ form.csrf_token() }}
		{{ form.hidden_tag() }}
		<div class="form-group">
			{{ form.username.label(class="form-control-label") }}
			{{ form.username(class="form-control", placeholder="username") }}
		</div>
		<div class="form-group">
			{{ form.password.label(class="form-control-label") }}
			{{ form.password(class="form-control", placeholder="******") }}
		</div>
		<div class="form-group">
			{{ form.submit(class="btn btn-secondary") }}
		</div>
	</form>
	<a href="{{ url_for('index') }}">
		<button class="btn btn-success my-2">Home</button>
	</a>
</div>
{% endblock %}